### ISSUE TITLE
Localization yml issue

### ISSUE THREAD

**Issue by viktorbrenek** [blaxxun-boop/Jewelcrafting#1]
Hi i have found an issue. Yml wont load up until i change my dots "." to "," also Item slots like "chest, head" etc need to have first letter in caps "Chest, Head" same goes for "Stagger Change" there you have to change the C also. Thats all. Otherwise works so far. Thanks bro

**Comment by blaxxun-boop** [comment]
Thanks for picking this up so quick. Fixed in v1.0.1.
