### ISSUE TITLE
[Bug] The Jewelbag allows teleporting of Boss Stones

### ISSUE THREAD

**Issue by himpich** [blaxxun-boop/Jewelcrafting#10]
Boss Jewels are not portable, just when used in a socket. The are unique, so you can socket only one at a time. 

The Jewelbag allows to put all boss jewels in a bag and port them (all at once)

**Comment by blaxxun-boop** [comment]
Boss gems are no longer non-teleportable. Not sure why there were non-teleportable to begin with.
