### ISSUE TITLE
Daring Gem ignoring Bosses stars in CLLC

### ISSUE THREAD

**Issue by GracefulUni** [blaxxun-boop/Jewelcrafting#100]
I have the stars maxed to 5 stars in CLLC but if i have Daring gems equipped they can spawn anywhere between 6-10 stars, can please get this fixed?

**Comment by blaxxun-boop** [comment]
This is on purpose. However, the next release of Jewelcrafting will add a config option that can be used to prevent daring from affecting bosses.
