### ISSUE TITLE
Effect chance config

### ISSUE THREAD

**Issue by jmc1421** [blaxxun-boop/Jewelcrafting#107]
hello brother!
me and my friends are really enjoying JC Mod!
and i'm curios about how can i modifying effect's chances? (Fire starter, snake bite, etc)
i tried to edit jewelcrafting.sockets.yml to

"fire starter:
  slot: [weapon, elementalmagic]
  gem: red
  power: [5, 7, 50]
   Optional Configs:
  chance: 100"
  
  and
  
  "fire starter:
  slot: [weapon, elementalmagic]
  gem: red
  power: [5, 7, 50]
  options:
    chance: 100"
   and various other methods
 but didn't works in game
    
 it can't be modifying by edit configs??
 
 
Besides that really thanks for your works!!

**Comment by blaxxun-boop** [comment]
```
fire starter:
  slot: [weapon, elementalmagic]
  gem: red
  power:
    power: [5, 10, 15]
    chance: [20, 20, 20]
