### ISSUE TITLE
[REQUEST] instructions for Jewelcrafting.Sockets.yml

### ISSUE THREAD

**Issue by matswib** [blaxxun-boop/Jewelcrafting#11]
Hi, awesome mod!

I'd like to change the costs of the standard gems (simple, advanced, perfect) but can't find it in the org.bepinex.plugins.jewelcrafting.cfg file.

And I can't find any instructions how to use the Jewelcrafting.Sockets.yml file. 
(It's empty not matter how many times I start the game)

Is it possible?

Br

**Comment by blaxxun-boop** [comment]
Create a file called `Jewelcrafting.Sockets.yml` in your config folder, toggle the external Yaml to on in the cfg file and paste the effects you want to change from the default config in there and adjust their values.
Default config is here: https://github.com/blaxxun-boop/Jewelcrafting/blob/master/Jewelcrafting/Effects/Jewelcrafting.Sockets.yml
So paste something like
```yml
fire starter:
  slot: weapon
  gem: red
  power: [10, 20, 30]
```
into your file, to double the damage of fire starter, for example.

**Comment by matswib** [comment]
Thanks, 

Too bad you couldn't change the non-shards gem recepies(always costs 1), but I loved that I could change the crystal spawn rates!
