### ISSUE TITLE
Socket add/Gem Upgrade change using Random.value leads to frustration

### ISSUE THREAD

**Issue by JesseMH** [blaxxun-boop/Jewelcrafting#12]
The plugin should ensure that probabilities occur as expected over a set number of tries, and allow that to be configured. E.g. with a 40% chance, and defining a # of tries as 1000, the event will occur 400 times. If the # of actual tries the player makes is under 1000, their successes might be more or less than 40%. 

Using Random.value to calculate chances to add sockets and to upgrade gems misleads players into thinking 50% means half of their attempts will be successful, however that may only be true after many thousands of attempts. This also may not be true for each player; given 2 players socketing items and a chance of 54%, after over 100 attempts each the total successes are expected to be 108, however it may be much higher or lower. Additionally if we assume 108 were actually successful there, one player might have a experienced really bad luck and produced 27 successfully while the other player had really great luck and produced 81, when the expectation is that they're both supposed to have succeeded 54 times each.

**Comment by JesseMH** [comment]
> @JesseMH 
> Where is it written about the fallout guarantee? I personally don't see it, so that's just your whining.
> 
> Even if you have a 99% probability, that doesn't mean you will have a hole after every 5 - 20 - 90 -120 times luck.
> 
> What I mean is. Random is random, so there's a 99% chance you'll have a few lucky attempts, but definitely not a guaranteed attempt after 50. Because it is random. Set up random? Then what's the point of these odds in the first place

If you think having a 40% success rate after 1000 attempts with a communicated ~53% chance of success is a satisfying mechanic for players, then ok.

**Comment by blaxxun-boop** [comment]
You won't get a 40% success rate after 1000 attempts with 53% chance to add a socket. Less than 0.0077% are below 47%. The distribution is actually quite good.
```
array (
  447 => 1,
  458 => 2,
  459 => 1,
  460 => 1,
  461 => 3,
  462 => 1,
  463 => 6,
  464 => 5,
  465 => 9,
  466 => 6,
  467 => 11,
  468 => 14,
  469 => 17,
  470 => 29,
  471 => 23,
  472 => 33,
  473 => 39,
  474 => 51,
  475 => 75,
  476 => 74,
  477 => 94,
  478 => 102,
  479 => 143,
  480 => 174,
  481 => 199,
  482 => 249,
  483 => 294,
  484 => 357,
  485 => 477,
  486 => 549,
  487 => 672,
  488 => 783,
  489 => 848,
  490 => 1069,
  491 => 1196,
  492 => 1360,
  493 => 1577,
  494 => 1847,
  495 => 2126,
  496 => 2508,
  497 => 2825,
  498 => 3215,
  499 => 3675,
  500 => 4156,
  501 => 4592,
  502 => 5254,
  503 => 5982,
  504 => 6482,
  505 => 7240,
  506 => 7887,
  507 => 8675,
  508 => 9509,
  509 => 10391,
  510 => 11382,
  511 => 12367,
  512 => 13216,
  513 => 14171,
  514 => 15049,
  515 => 15856,
  516 => 16999,
  517 => 17960,
  518 => 18854,
  519 => 19593,
  520 => 20623,
  521 => 21921,
  522 => 22287,
  523 => 22896,
  524 => 23291,
  525 => 23909,
  526 => 24288,
  527 => 24721,
  528 => 25113,
  529 => 25187,
  530 => 25319,
  531 => 25165,
  532 => 25362,
  533 => 24800,
  534 => 24302,
  535 => 24100,
  536 => 23577,
  537 => 22752,
  538 => 22346,
  539 => 21427,
  540 => 20705,
  541 => 20007,
  542 => 18951,
  543 => 17900,
  544 => 17073,
  545 => 16126,
  546 => 15203,
  547 => 14219,
  548 => 13358,
  549 => 12198,
  550 => 11289,
  551 => 10652,
  552 => 9694,
  553 => 8872,
  554 => 8102,
  555 => 7249,
  556 => 6259,
  557 => 5896,
  558 => 5278,
  559 => 4599,
  560 => 4228,
  561 => 3696,
  562 => 3247,
  563 => 2718,
  564 => 2504,
  565 => 2195,
  566 => 1883,
  567 => 1563,
  568 => 1374,
  569 => 1220,
  570 => 993,
  571 => 873,
  572 => 742,
  573 => 596,
  574 => 483,
  575 => 420,
  576 => 343,
  577 => 279,
  578 => 271,
  579 => 173,
  580 => 178,
  581 => 137,
  582 => 100,
  583 => 70,
  584 => 70,
  585 => 66,
  586 => 40,
  587 => 40,
  588 => 22,
  589 => 25,
  590 => 12,
  591 => 17,
  592 => 9,
  593 => 10,
  594 => 3,
  595 => 6,
  596 => 4,
  597 => 5,
  598 => 3,
  599 => 4,
  600 => 2,
  601 => 1,
  602 => 3,
  611 => 1,
)
```
That being said, I understand that some people think the current system is frustrating, because they will always have the feeling that the odds are against them and that they are part of the 0.00001% unlucky people. There will be other ways to add sockets to your items in future updates to accommodate that.
