### ISSUE TITLE
Floating Objects

### ISSUE THREAD

**Issue by Canis-Dirus** [blaxxun-boop/Jewelcrafting#13]
If you level an area where the Jewelcluster was and then it respawns it stays floating in the air instead of dropping to the ground. Flattening an area where a jewelcluster has already spawned causes it to fall to the ground but the respawned one later stays up.

**Comment by blaxxun-boop** [comment]
No, that's just how Valheim works. It might take up to 2-3 minutes, until they start to fall down, if there are a lot of objects in the area.
