### ISSUE TITLE
Documentation for Server admins wo create own events / override the default events?

### ISSUE THREAD

**Issue by himpich** [blaxxun-boop/Jewelcrafting#14]
With the new World Bosses came the Highlight "There are four different default events that rotate every two weeks. Server admins can create their own events to override the default events"

Can we get some documentation / examples for that? Or is it work in progress yet?

**Comment by blaxxun-boop** [comment]
You basically just create a file called Jewelcrafting.Gacha.yml in the config folder of your server.

Looks like this: https://github.com/blaxxun-boop/Jewelcrafting/blob/master/Jewelcrafting/WorldBosses/Jewelcrafting.Gacha.yml

You can either copy the top config, which is the default config and change the name and rewards or you can copy the example event at the bottom. Give it a nice name, a timespan when the event should be active and some rewards, done.

**Comment by himpich** [comment]
thanks!
