### ISSUE TITLE
Error with 1.3.7

### ISSUE THREAD

**Issue by bsleys** [blaxxun-boop/Jewelcrafting#16]
I getting the following error when interacting with a workbench or chest making then unusable in game, IE can't craft of use chests for example.

[Error  :  HarmonyX] Error while running static void ItemManager.Item::Patch_GetAvailableRecipesFinalizer(System.Collections.Generic.Dictionary<Recipe, BepInEx.Configuration.ConfigEntryBase> __state). Error: System.NullReferenceException: Object reference not set to an instance of an object
  at ItemManager.Item.Patch_GetAvailableRecipesFinalizer (System.Collections.Generic.Dictionary`2[TKey,TValue] __state) [0x0002b] in <b6cca3bf85994ce99fb7f72c5b8c1007>:0 
  at (wrapper dynamic-method) Player.DMD<Player::GetAvailableRecipes>(Player,System.Collections.Generic.List`1<Recipe>&)

**Comment by blaxxun-boop** [comment]
This is already fixed in Jewelcrafting. Unfortunately, it was a bug in ItemManager, so all mods that use it have to update, before it works again.

**Comment by bsleys** [comment]
Ok so if I follow correctly I need to figure out what other mods I have that also use ItemManager and update them all together else things break?

**Comment by blaxxun-boop** [comment]
Unfortunately, yes. If you give me a list of your mods, I can probably help you with that.

**Comment by DarthPresidente** [comment]
> 

@blaxxun-boop That did the trick.  Thank you!

**Comment by bsleys** [comment]
Here is my list.

Aedenthorn_Instant_Monster_Loot_Drop
Better_Trader_Remake
Blacksmithing
Clutter
Evasion
Farming
FermenterPercentage
FloatingItems
FloorsAreRoofs
Jotunn
Lumberjacking
MissingPieces
Network
OdinArchitect
OdinShip
OdinsQOL
OdinsSteelworks
OdinsTraps
Official_BepInEx_ConfigurationManager
PackHorse
PlantEverything
QuickConnect
Ranching
Sailing
SmoothSave
TargetPortal
Tenacity
TripleBronzeJVL
UseEquipmentInWater
Valheim.DisplayBepInExInfo.dll
ValheimRAFT
Vitality
ZeroBandwidth-CustomSeed
serverblankpassword

**Comment by blaxxun-boop** [comment]
@bsleys Steelworks just updated. Install the update and you should be fine.

**Comment by kdo12** [comment]
hi,  I don't know if that the same issue  but after update my character was blanked of everything. 

I got this:

[Error  : Unity Log] MissingMethodException: Constructor on type 'Jewelcrafting.Sockets' not found.
Stack trace:
System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Activator.CreateInstance (System.Type type, System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
ExtendedItemDataFramework.ExtendedItemData.Load () (at <5b0cbb9764ce4e05b5855c7d3cd40cf9>:0)
ExtendedItemDataFramework.ExtendedItemData..ctor (ItemDrop+ItemData prefab, System.Int32 stack, System.Single durability, Vector2i pos, System.Boolean equiped, System.Int32 quality, System.Int32 variant, System.Int64 crafterID, System.String extendedData) (at <5b0cbb9764ce4e05b5855c7d3cd40cf9>:0)
ExtendedItemDataFramework.Inventory_AddItemFromLoad_Patch.Prefix (Inventory __instance, System.Boolean& __result, System.String name, System.Int32 stack, System.Single durability, Vector2i pos, System.Boolean equiped, System.Int32 quality, System.Int32 variant, System.Int64 crafterID, System.String crafterName, System.Collections.Generic.Dictionary`2[TKey,TValue] customData) (at <5b0cbb9764ce4e05b5855c7d3cd40cf9>:0)
(wrapper dynamic-method) Inventory.DMD<Inventory::AddItem>(Inventory,string,int,single,Vector2i,bool,int,int,long,string,System.Collections.Generic.Dictionary`2<string, string>)
(wrapper dynamic-method) Inventory.DMD<Inventory::Load>(Inventory,ZPackage)
Container.Load () (at <035307060cbb4b30b916cd82ebd80490>:0)
Container.CheckForChanges () (at <035307060cbb4b30b916cd82ebd80490>:0)

**Comment by blaxxun-boop** [comment]
@kdo12 It's not. v1.3.7 of Jewelcrafting doesn't need ExtendedItemDataFramework anymore. It also doesn't work with Mistlands anymore, so you can remove it.

**Comment by kdo12** [comment]
thank for your answer, but when I remove it , my item  have some code about the gemthat where in it but thre not  here. sorry to ask you considering it  dont seem to be jewlcrating but I really don't know what to do. 

here the mod I have install 
azamutt evil katana
azamutt daedric et
azamutt lightsaber
azamutt mjolnir
bentog missingpieces
catalystbuildable
farmgrid
Mrseji construction
Candles_LanternsANDbeeswaxx
Smoothbrain-Jewelcrafting
Tekla-YamlDotNet
BuildIt
Torann_VL-Valheim_Legends
plant everything
jotunn

thank a lot

**Comment by blaxxun-boop** [comment]
@kdo12 Yes, that's normal. EIDF saved its data by writing it into the crafter name field. There is little you can do about that, unfortunately.

**Comment by kdo12** [comment]
ok, thank you so much, for your answer and the work put into it!

**Comment by kdo12** [comment]
But just to kwon, this you can't use item you make with the mod after every update?

**Comment by kdo12** [comment]
and I got this in red 

[Error  : Unity Log] ArgumentException: The Object you want to instantiate is null.
Stack trace:
UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation) (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation) (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
EffectList.Create (UnityEngine.Vector3 basePos, UnityEngine.Quaternion baseRot, UnityEngine.Transform baseParent, System.Single scale, System.Int32 variant) (at <035307060cbb4b30b916cd82ebd80490>:0)
WearNTear.RPC_Damage (System.Int64 sender, HitData hit) (at <035307060cbb4b30b916cd82ebd80490>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Delegate.DynamicInvokeImpl (System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Delegate.DynamicInvoke (System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
RoutedMethod`1[T].Invoke (System.Int64 rpc, ZPackage pkg) (at <035307060cbb4b30b916cd82ebd80490>:0)
ZNetView.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData rpcData) (at <035307060cbb4b30b916cd82ebd80490>:0)
ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <035307060cbb4b30b916cd82ebd80490>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <035307060cbb4b30b916cd82ebd80490>:0)
ZNetView.InvokeRPC (System.String method, System.Object[] parameters) (at <035307060cbb4b30b916cd82ebd80490>:0)
WearNTear.Damage (HitData hit) (at <035307060cbb4b30b916cd82ebd80490>:0)
Projectile.DoAOE (UnityEngine.Vector3 hitPoint, System.Boolean& hitCharacter, System.Boolean& didDamage) (at <035307060cbb4b30b916cd82ebd80490>:0)
(wrapper dynamic-method) Projectile.DMD<Projectile::OnHit>(Projectile,UnityEngine.Collider,UnityEngine.Vector3,bool)
Projectile.FixedUpdate () (at <035307060cbb4b30b916cd82ebd80490>:0)

**Comment by blaxxun-boop** [comment]
Okay, but that's enough reporting of issues unrelated to Jewelcrafting here now.
