### ISSUE TITLE
[bug] Error with new Extended Item Data Framework 1.0.9

### ISSUE THREAD

**Issue by matswib** [blaxxun-boop/Jewelcrafting#18]
Tried to switch to Mistlands but the old EIDF dependent Jewelcrafting socketed items throw errors:

"[Error  : Unity Log] MissingMethodException: Constructor on type 'Jewelcrafting.PositionStorage' not found.
Stack trace:
System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Activator.CreateInstance (System.Type type, System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
ExtendedItemDataFramework.ExtendedItemData.Load () (at <5961e71cf2564955a79771e978d661b5>:0)
ExtendedItemDataFramework.ExtendedItemData..ctor (ItemDrop+ItemData prefab, System.Int32 stack, System.Single durability, Vector2i pos, System.Boolean equiped, System.Int32 quality, System.Int32 variant, System.Int64 crafterID, System.String extendedData) (at <5961e71cf2564955a79771e978d661b5>:0)
ExtendedItemDataFramework.Inventory_AddItemFromLoad_Patch.Prefix (Inventory __instance, System.Boolean& __result, System.String name, System.Int32 stack, System.Single durability, Vector2i pos, System.Boolean equiped, System.Int32 quality, System.Int32 variant, System.Int64 crafterID, System.String crafterName, System.Collections.Generic.Dictionary`2[TKey,TValue] customData) (at <5961e71cf2564955a79771e978d661b5>:0)
(wrapper dynamic-method) Inventory.DMD<Inventory::AddItem>(Inventory,string,int,single,Vector2i,bool,int,int,long,string,System.Collections.Generic.Dictionary`2<string, string>)
(wrapper dynamic-method) Inventory.DMD<Inventory::Load>(Inventory,ZPackage)
(wrapper dynamic-method) Player.DMD<Player::Load>(Player,ZPackage)
PlayerProfile.LoadPlayerData (Player player) (at <035307060cbb4b30b916cd82ebd80490>:0)
(wrapper dynamic-method) Game.DMD<Game::SpawnPlayer>(Game,UnityEngine.Vector3)
Game.UpdateRespawn (System.Single dt) (at <035307060cbb4b30b916cd82ebd80490>:0)
Game.FixedUpdate () (at <035307060cbb4b30b916cd82ebd80490>:0)"

Load log new Mistlands:
[Info   :   BepInEx] Loading [Extended Item Data Framework 1.0.9]
[Info   :   BepInEx] Loading [Jewelcrafting 1.3.8]
[Info   :   BepInEx] Loading [Soulcatcher 4.1.0]

Load log old H&H:
[Info   :   BepInEx] Loading [Extended Item Data Framework 1.0.7]
[Info   :   BepInEx] Loading [Jewelcrafting 1.3.5]
[Info   :   BepInEx] Loading [Soulcatcher-JC-Addtiions 3.1.0]

Is there anything I can do or are all socketed items lost?
(If I dont add EIDF the items are still corrupted but throws no error)

**Comment by himpich** [comment]
Same here without  EIDF: all sockets and contents not shown (but seem to be in extended information)
latest EIDF: lots of errors - not usable and inventory empty

using jewelcrafting + soulcatcher

**Comment by blaxxun-boop** [comment]
EIDF is an obsolete mod, you can simply remove it. It's not used by Jewelcrafting anymore. Instead, it uses Valheims native way to store the information now. Unfortunately, there is no conversion between the two systems.
