### ISSUE TITLE
Crash with Backpack Redux

### ISSUE THREAD

**Issue by davidtaylornc** [blaxxun-boop/Jewelcrafting#20]
When opening backpack extended section and moving items back and forth, null object exception occurs due to traversing uninitialized inventory squares.

1. Exception in private static void UpdateElement(ItemDrop.ItemData item, GameObject root)
fails at item.Data().Get<Sockets>(); and GetComponent<Image>().color;

2.  Exception  in ColorBackgroundInventory.Postfix inside foreach (InventoryGrid.Element element in __instance.m_elements.Where(element => !element.m_used))

**Comment by blaxxun-boop** [comment]
Just use https://valheim.thunderstore.io/package/Smoothbrain/Backpacks/
