### ISSUE TITLE
Gem properties don't show in the description

### ISSUE THREAD

**Issue by Urfin13** [blaxxun-boop/Jewelcrafting#21]
Hi, I'm having a problem running Jewelcrafting on a dedicated server - the gem properties don't show in the description. This only happens on a server, if I run locally it's fine.

![jewelcrafting bug](https://user-images.githubusercontent.com/30248678/207391034-0966a4ec-85ed-465a-a78e-b9874d406d44.jpg)

It works ok without other mods, so it seems to be a problem with one of my other mods. Could I trouble you to point out the likely suspects so I can test?

My modlist:

BepInExPack_Valheim
Official_BepInEx_ConfigurationManager
Jotunn
WackysDatabase
CreatureLevelAndLootControl
OdinShip
CraftyCartsRemake
OdinTrainingPlace
Better_Trader_Remake
Digitalroot_Valheim_SlopeCombatFix
TripleBronzeJVL
AtosArrowsJVL
fastercrafting
FastTeleport
HearthStone_Revived
TargetPortal
Skald
AzuContainerSizes
InstantEquip
ValheimPlus
OdinsTraps
OdinsBarrelRide
Stone_Portal
CraftableChainReuploadFromNexus
Pathfinder
Stump_Grinder
Resurrection
DarwinAwards
SteadyRegeneration
Vitality
Tenacity
Farming
Evasion
DualWield
Building
Mining
Lumberjacking
PackHorse
Blacksmithing
PassivePowers
Jewelcrafting
QuickStack
SpeedyPaths
ItemDrawers
OdinCampsite
Rune_Magic
ComfyQuickSlots
PotionPlus
OdinsSteelworks
Digitalroot_Valheim_MaxDungeonRooms
Blacksmiths_tools
Judes_Equipment

**Comment by blaxxun-boop** [comment]
Do they have any effect, if you socket them into your equipment or do they all say "no effect"? If they all say "no effect" it's very likely Valheim Plus. It's just a terrible mod that conflicts with a lot of other mods, in a very deceitful way. It doesn't print stacktraces, if it messes stuff up, like normal mods do, but hides them and blames other mods for the issues.

**Comment by Urfin13** [comment]
Confirmed it was plus, thanks for the tip! And for the mods, they are exactly what's needed.
