### ISSUE TITLE
Item gets "stuck" on cursor (sometimes)

### ISSUE THREAD

**Issue by SkyeMors** [blaxxun-boop/Jewelcrafting#23]
Log chunk:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Jewelcrafting.SocketsBackground.UpdateElement (ItemDrop+ItemData item, UnityEngine.GameObject root) (at <58fe6154dcda4654ae5a5833101eed1a>:0)
Jewelcrafting.SocketsBackground+ColorBackgroundInventory.Postfix (InventoryGrid __instance) (at <58fe6154dcda4654ae5a5833101eed1a>:0)
(wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::UpdateGui>(InventoryGrid,Player,ItemDrop/ItemData)
InventoryGrid.UpdateInventory (Inventory inventory, Player player, ItemDrop+ItemData dragItem) (at <035307060cbb4b30b916cd82ebd80490>:0)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::UpdateContainer>(InventoryGui,Player)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Update>(InventoryGui)

Steps to reproduce:
Unknown

Gameplay effect:
When dragging an item in the inventory, the action will perform as normal- BUT when dropped, the item will appear to still be in the cursor, breaking UI inventory interactions so items cannot be picked up. This extends to extended inventories (gem bag and Backpack from another mod) not having ItemDescriptions shown.

Temporary fix:
Re-log. (Logout, reload world, avoid using the cursor to "hold" items and only Ctrl+Click to move items)

Attempting workaround:
Turning off Custom Item Backgrounds (or whatever) in the Config.
Workaround failed, friend still has bug. I haven't gotten it yet since the change, but he's got the same mods and configs, so I assume it's because I was in Singleplayer.

Update:
Friend and I are tearing our respective hair out trying to reliably replicate it- he'll hop on, it'll happen, he'll re-log, try to cause it to happen- and it won't. Then the next day he'll just try to play the game, and get it non-stop through multiple re-logs, then I end up getting it.

**Comment by comfymarkus** [comment]
Seeing the same exception spam with my friends and I randomly, not sure what is causing it.

**Comment by blaxxun-boop** [comment]
This has been addressed in v1.3.9
