### ISSUE TITLE
not sure what started this red code

### ISSUE THREAD

**Issue by cogzin** [blaxxun-boop/Jewelcrafting#25]
[Error  : Unity Log] MissingMethodException: Constructor on type 'Jewelcrafting.Sockets' not found.
Stack trace:
System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Activator.CreateInstance (System.Type type, System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
ExtendedItemDataFramework.ExtendedItemData.Load () (at <5961e71cf2564955a79771e978d661b5>:0)
ExtendedItemDataFramework.ExtendedItemData..ctor (ItemDrop+ItemData prefab, System.Int32 stack, System.Single durability, Vector2i pos, System.Boolean equiped, System.Int32 quality, System.Int32 variant, System.Int64 crafterID, System.String extendedData) (at <5961e71cf2564955a79771e978d661b5>:0)
ExtendedItemDataFramework.Inventory_AddItemFromLoad_Patch.Prefix (Inventory __instance, System.Boolean& __result, System.String name, System.Int32 stack, System.Single durability, Vector2i pos, System.Boolean equiped, System.Int32 quality, System.Int32 variant, System.Int64 crafterID, System.String crafterName, System.Collections.Generic.Dictionary`2[TKey,TValue] customData) (at <5961e71cf2564955a79771e978d661b5>:0)
(wrapper dynamic-method) Inventory.DMD<Inventory::AddItem>(Inventory,string,int,single,Vector2i,bool,int,int,long,string,System.Collections.Generic.Dictionary`2<string, string>)
(wrapper dynamic-method) Inventory.DMD<Inventory::Load>(Inventory,ZPackage)
Container.Load () (at <035307060cbb4b30b916cd82ebd80490>:0)
Container.CheckForChanges () (at <035307060cbb4b30b916cd82ebd80490>:0)

**Comment by blaxxun-boop** [comment]
ExtendedItemDataFramework started it. It's not needed by Jewelcrafting anymore.
