### ISSUE TITLE
sockets are removed when teleporting

### ISSUE THREAD

**Issue by paul-cpp** [blaxxun-boop/Jewelcrafting#28]
Hi! A found a bug. If you drop your equipment on the ground and use the portal, when you return, all sockets will be removed from it.
Could you please check it?

By the way, I use TargetPortal mod for teleportation (https://valheim.thunderstore.io/package/Smoothbrain/TargetPortal/1.1.6/) but I don't think it has any effect

**Comment by Lime18** [comment]
![image](https://user-images.githubusercontent.com/29817277/209444471-5ab7fa05-7139-499c-9553-d86a05f477bb.png)
![image](https://user-images.githubusercontent.com/29817277/209444479-23adfc83-8236-4307-968d-29a91b440c41.png)
![image](https://user-images.githubusercontent.com/29817277/209444497-c66def98-baef-486f-b71f-5edd4d4cfca1.png)
the same problem

**Comment by Lime18** [comment]
![image](https://user-images.githubusercontent.com/29817277/209444535-0d0283ab-2455-4f6e-86fb-56de025c4f41.png)
If you put it in the chest, it's fine

**Comment by blaxxun-boop** [comment]
Fixed in v1.3.10, thanks.
