### ISSUE TITLE
chests inacessible, all slots have a white jewel icon on them, load list as follows

### ISSUE THREAD

**Issue by ThalassicRaysOfTheAphoticSunset** [blaxxun-boop/Jewelcrafting#29]
[LogOutput.log](https://github.com/blaxxun-boop/Jewelcrafting/files/10300316/LogOutput.log)

**Comment by blaxxun-boop** [comment]
This is usually due to mods modifying the inventory space and has nothing to do with Jewelcrafting.
E.g., if you have a mod that adds an additional inventory row, put items in that row and then remove said mod, this is exactly what happens.

Dying to clear out the inventory can help in this case.
