### ISSUE TITLE
Jewel Crafting Table Recipe suggestions

### ISSUE THREAD

**Issue by DMSiafu** [blaxxun-boop/Jewelcrafting#3]
Not really an Issue, but might i suggest you change the recipe for the Jewel crafting table to require some of each of the uncut jewels to craft? it feels as if the table itself is really cheap to make, and it would also slightly gate it so most players will need to kill Eikthyr before unlocking the table.

Also, with the prevalence of the gem nodes, maybe make each of the higher tiers cost more gems to craft.

**Comment by Lucas-UFU** [comment]
Recipe ok

**Comment by Lucas-UFU** [comment]
Cost configurable boy server files

**Comment by DMSiafu** [comment]
i understand that the recipe can be changed in the config, i was just saying that it might be better to have it cost the gems by default.
