### ISSUE TITLE
MissingMethodExeption

### ISSUE THREAD

**Issue by gLozeen** [blaxxun-boop/Jewelcrafting#30]
I encountered one error that happens for reason I don't understand. I'll attach screenshots below. If you need any additional information please write.
![geas](https://user-images.githubusercontent.com/121202185/209479001-72912876-17ff-4927-b1f8-269c4f22a5f8.png)
![geas2](https://user-images.githubusercontent.com/121202185/209479003-0a1d6c3d-4f15-4e1e-a114-ce0dfbe92798.png)

**Comment by blaxxun-boop** [comment]
As you can see, the issue is with ExtendedItemDataFramework. Just remove that mod.
