### ISSUE TITLE
Unique gem effects can be disruptive

### ISSUE THREAD

**Issue by aaronransley** [blaxxun-boop/Jewelcrafting#31]
Hiya, love the mod, thank you so much for the amazing work!

I have noticed that the unique gem effects can get a bit overwhelming when I'm puttering around the ol' base, just planting trees or getting into a build. For example, the Eikthyr's Lightning will trigger on my helm while trying to line up a snap point, and I'll go zipping off in some direction! 

In this case, it's the gems status effect (wildly quick run speed) that can be a bit surprising when not out for a forage or doing exploration.

Another example with the Elder ability (whose gem name I can't recall), which will spawn spiraling, floating skulls and play doomy SFX. Yikes, does my garden really look that bad?? 💀 

This said, I'm not really sure what the solution here is. I can of course take off my armor or other gear that has the gem equipped, but I wonder if you have any ideas for "context sensitive" gem effects? 

- Could gems be configured to only apply when X meters from a player building?
- Only apply while in combat or if hostile creatures are nearby?
- Some, or all gem effects toggled on and off with a hotkey?
- Could certain, powerful gem effects be setup as active abilities, with their own separate hotkey & cooldown?

Absolute brainstorm here, so please take with a grain of salt! I know next to nothing about effort involved in all these things, but thought I'd drop a note either way.

Anyways, much love to the mod and thank you so much for the time + energy! My partner and I have had a wonderful time playing a fresh world filled with gems and mystery (and potions, thanks to your PotionsPlus!)

**Comment by blaxxun-boop** [comment]
Fixed in v1.3.16
