### ISSUE TITLE
Vampire and Berserk effects appears to be using the wrong gems

### ISSUE THREAD

**Issue by arruda** [blaxxun-boop/Jewelcrafting#32]
It seems like the Vampire effect should be using the purple gem by default (based on the description of the synergy effect). And the berserk should be using the Yellow gem (from the thematic of the gem)

Also, a bit unrelated to this, but I tried to change this in the `Jewelcrafting.Sockets.yml` file, and I ended up with both effects in both gems. 
It seems like there is a merge going on between the default configs and the new ones, such that I get the default vampire and berserk in the yellow and purple, and the new vampire and berserk config in the other purple and yellow.

**Comment by blaxxun-boop** [comment]
No, but you have to unbind the old gem, to remove the effect from it.

E.g. moving Vitality from Blue to Red:
```
vitality:
  - slot: []
    gem: blue
  - slot: chest
    gem: red
    power: [3, 5, 7]
```
