### ISSUE TITLE
Comfortite and Comfordium have invalid recipes in 1.3.17

### ISSUE THREAD

**Issue by bonesbro** [blaxxun-boop/Jewelcrafting#33]
The recipes for cutting simple comfortite and comfordium show no input materials on the gemcrafting table and the crafting recipe fails to work.  Worked in 1.3.15.

**Comment by blaxxun-boop** [comment]
Comfortite and Comfordium are added by Comfort Tweaks, not Jewelcrafting.

**Comment by bonesbro** [comment]
Thanks - would be great if you could keep a changelist and/or github for that one.  It's one of the few mods you have that isn't public.

**Comment by blaxxun-boop** [comment]
It's not my mod, sorry.

**Comment by bonesbro** [comment]
BTW - the source of the issue is that the other mod changed the name of the gems and the recipes are saved into the Jewelcrafting config file.  So after upgrading the config file was left with the old, invalid recipes.  The fix was to remove them from the config file, allowing them to be regenerated with the new recipes.
