### ISSUE TITLE
Wrong effect description or lost in translation?

### ISSUE THREAD

**Issue by OukPanBrouk** [blaxxun-boop/Jewelcrafting#34]
Hallo
1)  I'm not sure what effect "Lonely" should do. Description say:

jc_se_group_loneliness: "Lonely"
jc_se_group_loneliness_description: "Movement speed reduced by $7% and damage taken increased by $8%." (100% in game)

But when "Lonely" effect on my character is activ, my char do 0 (Zero) demage to any target. Or should my char take 100% more demage (it's how I understand phrase "damage taken". Am I just lost in translation?)

2) In my Megingjord I have one Perfect Spinel (Hercules) with 20% more carry weight and one Advanced Spinel with 15% more carry weight. Together 35% more carry weight but Activ sockets Tab says:

Carry weight is increased by **38%**.

If I use just one Spinel Activ sockets tab shows the right numbers. 
Perfect spinel:
Carry weight is increased by 20%.
Advanced Spinel:
Carry weight is increased by 15%.

Thank you for your great mods. Possibility of configuration your mods is insane (in really good way)

Ouk

**Comment by blaxxun-boop** [comment]
For Lonely: It actually does both, the part where you do not deal any damage is just missing from the description. I can change that and possibly reduce the debuff as well.

For the carry weight:
100 * 1.2 = 120
120 * 1.15 = 138
So all good here.

Cheers.

**Comment by OukPanBrouk** [comment]
Reducing the buff would be great. Movement speed reduction and increased damage taken is already tough if you are in the heat of battle. Plus 20-30% demage given reduction will be ok.

100 * 1.2 = 120
120 * 1.15 = 138
So all good here..........I knew there is reason why.

Thx for explanation and your time.
Ouk
