### ISSUE TITLE
Incompatible with DasSauerkraut.Terraheim

### ISSUE THREAD

**Issue by Mar1cX** [blaxxun-boop/Jewelcrafting#36]
Hi, noticed that Jewelcrafting is not compatible with DasSauerkraut.Terraheim, while EpicLoot does seem to try to attempt that. Is there a plan to make both of those mods compatible - Jewelcrafting&Terraheim (for Mistlands DasSauerkraut_Terraheim by blacks7ar is used)?

[Error  :   BepInEx] Could not load [Jewelcrafting 1.3.22] because it is incompatible with: DasSauerkraut.Terraheim

**Comment by blaxxun-boop** [comment]
You would have to ask the author of Terraheim to fix this. If you load both mods at the same time, Terraheim prevents you from crafting any items, because of this bug:
https://github.com/DasSauerkraut/Terraheim/blob/master/Patches/CraftingPatch.cs#L25

**Comment by DasSauerkraut** [comment]
Hey, dev of Terraheim here. Just chiming in to let you know that the crafting patch is disabled with the latest release if you want to remove the incompatible tag.

**Comment by blaxxun-boop** [comment]
@DasSauerkraut Thanks for the heads up, will do.
