### ISSUE TITLE
Feature request: Convert Trader items (Megingjorg, Dverger circlet, wishbone) to jewels

### ISSUE THREAD

**Issue by bonesbro** [blaxxun-boop/Jewelcrafting#37]
It would be really useful if we could convert the other Vanilla utility slot items into jewels, similar to the new implementation of the wisplight.  That would increase the viability of the necklaces & rings that you can craft with perfect gems.  I find that I rarely use them because carry weight is usually critical.  There are also a limited number of utility gems and it would be nice to introduce more options for that slot.

Hmm, maybe the Circlet would be a helm gem instead.

**Comment by blaxxun-boop** [comment]
Sounds good to me. I will add that to my to-do list.

**Comment by blaxxun-boop** [comment]
Done.
