### ISSUE TITLE
Conflict with WisplightSlot functionality

### ISSUE THREAD

**Issue by carpenteer** [blaxxun-boop/Jewelcrafting#38]
With Jewelcrafting updated to 1.3.22, with the new Wisplight as a gem feature disabled, the WisplightSlot mod doesn't work.  No errors in the log, it simply no longer lets you equip it to its own slot and instead switches with whatever utility item you had equipped.  The sister mod to WisplightSlot (both use nearbear's CustomSlotItemLib) still works as expected, so the conflict is specific to wisp lights.

**Comment by razgrim** [comment]
Just verified - still can't equip wisplight with JC 1.4.8 as only mod.

**Comment by blaxxun-boop** [comment]
Yes, you do not need the Wisplight Slot mod, if you are using JC. Just socket it into your belt or whatever, so you have both effects as well.
