### ISSUE TITLE
Killing tamed animals start a loop

### ISSUE THREAD

**Issue by DuskTakee** [blaxxun-boop/Jewelcrafting#40]
On the last update 1.4.2 with equipment drops on when you kill a tamed animal with a weapon or if its killed by any monster it start a death loop,  the tamed animal will become imortal with 0 hp and will repeat the cry and the drops spawn until the game crashes

**Comment by DuskTakee** [comment]
[Player.log](https://github.com/blaxxun-boop/Jewelcrafting/files/10668887/Player.log)

**Comment by DuskTakee** [comment]
[Player.log](https://github.com/blaxxun-boop/Jewelcrafting/files/10668907/Player.log)

**Comment by DuskTakee** [comment]
----- 5x -----
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
--------------

[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Warning: Unity Log] 02/06/2023 16:55:48: Missing audio clip in music respawn

----- 632x -----
[Error  : Unity Log] KeyNotFoundException: The given key was not present in the dictionary.
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Jewelcrafting.LootSystem.Drop+AddEquipmentDrop.Postfix (CharacterDrop __instance) (at <a42e48ef17b24fc3ab310c89d25cf144>:0)
(wrapper dynamic-method) CharacterDrop.DMD<CharacterDrop::OnDeath>(CharacterDrop)
(wrapper dynamic-method) Character.DMD<Character::OnDeath>(Character)
Character.CheckDeath () (at <35c0f7aa1999477788815a7bf78200d7>:0)
(wrapper dynamic-method) Character.DMD<Character::FixedUpdate>(Character)
Humanoid.FixedUpdate () (at <35c0f7aa1999477788815a7bf78200d7>:0)
----------------

**Comment by blaxxun-boop** [comment]
Was fixed in ... 1.4.3?
