### ISSUE TITLE
Vitality Skill is not compatible with Jewelcrafting. Health modifications from gems are applied twice

### ISSUE THREAD

**Issue by AzumattDev** [blaxxun-boop/Jewelcrafting#42]
My health here should be 32, not 39.

![image](https://user-images.githubusercontent.com/80414405/218187903-0af1bf6e-0d20-4fb3-b459-83a2a16e5789.png)

**Comment by blaxxun-boop** [comment]
Made Jewelcrafting fully compatible with Vitality.
