### ISSUE TITLE
Status Effect Management is causing Frameloss due to aggressive management

### ISSUE THREAD

**Issue by Vapok** [blaxxun-boop/Jewelcrafting#44]
In Jewelcrafting, the Postfix for `Humanoid.ShowHandItems` is recalculating effects nonstop essentially spamming RemoveStatusEffects for every effect registered regardless of whether the effect was applied.

As an example, the Postfix here:

```csharp
    [HarmonyPriority(Priority.Low)]
    private static void Postfix(Humanoid __instance)
    {
        if (__instance is Player player && (player == Player.m_localPlayer || !ZNetScene.instance))
        {
            CalculateEffects(player);
        }
    }
```

Is calling `API.OnEffectRecalc()` on every effect in nearly every frame that your hands are out except when swimming.

Here is the Wisplight effect as an example:

```csharp
static Wisplight()
    {
        API.OnEffectRecalc += () =>
        {
            if (Jewelcrafting.wisplightGem.Value == Jewelcrafting.Toggle.On)
            {
                if (Player.m_localPlayer.GetEffect(Effect.Wisplight) == 0)
                {
                    Player.m_localPlayer.m_seman.RemoveStatusEffect("Demister");
                }
                else
                {
                    Player.m_localPlayer.m_seman.AddStatusEffect("Demister");
                    if (Player.m_localPlayer.m_seman.GetStatusEffect("Demister") is SE_Demister demister)
                    {
                        demister.m_maxDistance = Player.m_localPlayer.GetEffect(Effect.Wisplight);
                    }
                }
            }
        };
    }
```

This is removing status effects placed by other mods that also manage effects.

**Suggestion:**
Instead of issuing the RemoveStatusEffect every single frame, only recalculate effects when it's needed, like on the `Humanoid.UpdateEquipmentStatusEffects()` method.

Then only apply effects that are needed and let the game handle removes on its own.

This would also prevent other mods from having to implement and manage a Prefix Patch for RemoveStatusEffects() in order to block the removal from Jewelcrafting.

As an example, this is how Advanced Backpacks is managing effects.

https://github.com/Vapok/AdventureBackpacks/blob/3499a0ac5ad52bf6ec0a3ebbfa151498c2b0478f/AdventureBackpacks/Patches/Humanoid.cs#L12-L57

This the `Humanoid.UpdateEquipmentStatusEffects` Transpiler that Adventure Backpacks uses, which can be safely dropped into any mod, requires a single method that returns a `HashSet<StatusEffect>` of all status effects that _should_ be applied. 

You could easily refactor CalculateEffects method to return HashSet<StatusEffect> from this method and have the resulting API.OnEffectCalc output the status effect for that Gem as part of the output.

This would allow the method to run only on equipment changes, and can also be run manually to refresh effects if there is an event that requires it.

Obviously, this is just a suggestion.  Thanks!

**Comment by blaxxun-boop** [comment]
What makes you think ShowHandItems is called every frame? Do you have a mod which does that?
