### ISSUE TITLE
Console error (thunderstore version

### ISSUE THREAD

**Issue by frankiesek** [blaxxun-boop/Jewelcrafting#45]
[Error  : Unity Log] Found Jewelcrafting config errors in built-in Synergies config. Please report the issue:
Found no valid operator at offset 0 (starting at: 'red > 5') for condition 'red > 5'. Allowed operators are: 'and', '<=', '>=', 'or', '*', '/', '+', '-', '<', '>', '='. Found in synergy 'at least six red and no blue'.
Found no valid operator at offset 0 (starting at: 'yellow = 3') for condition 'yellow = 3'. Allowed operators are: 'and', '<=', '>=', 'or', '*', '/', '+', '-', '<', '>', '='. Found in synergy 'exactly three yellow'.
Found no valid operator at offset 0 (starting at: 'red > purple + black') for condition 'red > purple + black'. Allowed operators are: 'and', '<=', '>=', 'or', '*', '/', '+', '-', '<', '>', '='. Found in synergy 'more red than black and purple combined'.
Found no valid operator at offset 0 (starting at: 'green = blue') for condition 'green = blue'. Allowed operators are: 'and', '<=', '>=', 'or', '*', '/', '+', '-', '<', '>', '='. Found in synergy 'same number of green and blue'.
Found no valid operator at offset 0 (starting at: 'yellow = black * 2') for condition 'yellow = black * 2'. Allowed operators are: 'and', '<=', '>=', 'or', '*', '/', '+', '-', '<', '>', '='. Found in synergy 'twice as much yellow than black'.
Found no valid operator at offset 0 (starting at: 'purple > max other') for condition 'purple > max other'. Allowed operators are: 'and', '<=', '>=', 'or', '*', '/', '+', '-', '<', '>', '='. Found in synergy 'purple as the most common'.

**Comment by blaxxun-boop** [comment]
It's very likely that there are other errors before that, which cause this.

**Comment by frankiesek** [comment]
Nope. Bunch of Information/Message, but no warning or error before this.
