### ISSUE TITLE
Req: config option for synergies tab

### ISSUE THREAD

**Issue by Darrken** [blaxxun-boop/Jewelcrafting#46]
The synergy tab attached to the inventory conflicts with at least one trash mod (e.g. quick/stack/store/sort/trash's trash tab) and overwrites their display. It would be great to see config options for position and/or a toggle.

![image](https://user-images.githubusercontent.com/797074/222543390-9b558d61-a246-4358-9c30-0767a7475ba1.png)

**Comment by blaxxun-boop** [comment]
Not unintentionally lucky, but exactly what I've implemented to make sure that Jewelcrafting doesn't conflict with trash mods. 😉
