### ISSUE TITLE
Most keys + mouse turning doesn't work with Jewelcrafting installed

### ISSUE THREAD

**Issue by razgrim** [blaxxun-boop/Jewelcrafting#49]
Broke as soon as Valheim 214.2 dropped, broken for tested Jewelcrafting versions 1.3.16 and 1.4.6
Problems: Can't turn character (using mouse). Most keys don't work, WASD do, all others (escape, tab, F, numbers) do not. 
Verified running Jewelcrafting as only mod on BepInEx, both new and old games, new world. Other players on server reported same issue. 
Problem fixed as soon as removing mod on client. 

Our players love this mod and would hate to be without it, not sure what further troubleshooting I can provide other than the above repro steps.

**Comment by blaxxun-boop** [comment]
Yes, v1.3.16 probably doesn't work anymore. v1.4.6 works perfectly fine on the latest Valheim patch.
