### ISSUE TITLE
Socket refund amount.

### ISSUE THREAD

**Issue by DMSiafu** [blaxxun-boop/Jewelcrafting#5]
Just testing the mod, i've noticed that when you set the refund amount for failed socketing pieces of gear to 100%, it is only 100% of the base cost, not the cost of any piece of armor that may be upgraded. a level 3 Bronze Cuirass should refund a total of 14 bronze and 2 deer hide, but instead only refunds 5 bronze and 2 deer hide.

Early game that isn't much of an issue, but after getting into the swamps that starts to become more problematic. i know there are a few mods that offer recycling to refund materials, so you may be able to see what they did to get the proper material amounts.

**Comment by DMSiafu** [comment]
Also, just noticed that sometimes when adding a socket to an item, a random item in the list will get leveled above the in-game maximum. It just made my Fine Wood Bow (which was level 4) go to level 24 now.

**Comment by blaxxun-boop** [comment]
Added a config option to return resources spent on upgrades as well.
