### ISSUE TITLE
Suspected poor interaction with Equipment and Quick Slots

### ISSUE THREAD

**Issue by DiskImage** [blaxxun-boop/Jewelcrafting#55]
I have Equipement and Quickslots v2.1.5 installed alongside jewlcrafting 1.4.8 and have noticed some interactions that are probably caused by some difference in how the items in the added slots behave. For example, my jewelcrafting bag doesn't pick up jewels automatically when I have it equipped to the utility slot, only when unequipped in my inventory. I also can't open the bag while it's equipped to my utility slot, only when it's in the general inventory.

I couldn't figure out why the Secret Pocket effect didn't do anything but then had the idea that it might be related to the jewelbag issues. If you're supposed to be able to open it with E while equipped, then it'd make sense that I can't use the effect if the equipment slots fail to trigger the jewelcrafting behavior. Not entirely sure about the cause, but here's my thunderstore profile to use for recreation: `01879b01-3651-108e-0163-7b19adc52a98`

**Comment by blaxxun-boop** [comment]
Equipment and Quickslots is the worst implementation of that feature. I highly recommend to switch to one of the alternatives, e.g. AzuExtendedInventory, if you don't want to lose your items, if you die. It also has way fewer conflicts.

And "Secret Pocket" is added by Comfort Tweaks. It simply increases your carry weight while you are rested.
