### ISSUE TITLE
Not an issue but info request for Boss ID's for experience mods config

### ISSUE THREAD

**Issue by draco1122** [blaxxun-boop/Jewelcrafting#57]
Not an issue but requesting info for Boss ID's for experience mods config. So killing bosses grants experience. Mod I need ID's for is Leveling and Experience mod.  Link here https://www.nexusmods.com/valheim/mods/2282

**Comment by blaxxun-boop** [comment]
Crystal_Frost_Reaper
Crystal_Fire_Reaper
Crystal_Soul_Reaper
