### ISSUE TITLE
Feature Request - Loot Option: Equipment (Empty)

### ISSUE THREAD

**Issue by Havengrad** [blaxxun-boop/Jewelcrafting#64]
We currently have Gem Drops and Equipment Drops. (With being able to choose one or the other or both) And while this is brilliant I would request the ability to have Equipment drops, without gems in them. For whatever reason most gear that drops has a high chance to, be all combination gems, max sockets, full of gems, and lean heavily towards higher quality gems. Kind of flooding the player with gems and significantly skewing the player away from actually bothering to cut any themselves.

The recent option to disallow removing of the gems from dropped items is a welcome one but might not appeal to all.

Simply I'd propose an option for empty equipment drops, likely with a random skew of sockets ranging from 0 to whatever the max in the config is. This makes drops useful, but not cluttering, while still preserving the need to actually engaging with the jewelcrafting part of jewelcrafting. This might benefit even more from having some sort of skew of gems vs equipment drops or at least a drop chance slider for both, so one can as an example, make drops less common than gems themselves.

**Comment by blaxxun-boop** [comment]
Sounds like your creatures have way more health than they do in vanilla. Just use the config options to adjust for that.

**Comment by Havengrad** [comment]
I will look into this.
