### ISSUE TITLE
JC questions - 2.0 & loot

### ISSUE THREAD

**Issue by Oosquai** [blaxxun-boop/Jewelcrafting#65]
Hi blaxxun-boop!
I'm setting up a fresh modded server for a bunch of friends, and I'm excited to try Jewelcrafting instead of that other mod this time around!  Could I ask a few questions please?
- Any guesses when Jewelcrafting 2.0 will be ready?
- If I use mods that add enemies, will those new enemies be able to drop gear with sockets?
- If I use mods that add weapons and armor, will those additions be able to drop with sockets from enemies?
Thank you!

**Comment by blaxxun-boop** [comment]
No idea when JC 2.0 will be done.

Modded items should drop out of the box, if they use vanilla items for crafting them. If the mod adds new materials that are used to craft the new armor or weapons, then you have to add that material to the biome where you want the crafted items to drop in the YAML config.

**Comment by Oosquai** [comment]
Awesome, thank you so much!  I'll work with the YAML file as needed.  Thanks for all the work you do adding to Valheim!

**Comment by blaxxun-boop** [comment]
It's this file: https://github.com/blaxxun-boop/Jewelcrafting/blob/master/Jewelcrafting/LootSystem/Jewelcrafting.Loot.yml
Works the same way as the Jewelcrafting.Sockets.yml. Just copy and paste the file into your config folder, adjust it and make sure external yaml is on in the cfg file.
