### ISSUE TITLE
Take All button defeats Unsocket Dropped Items=Off

### ISSUE THREAD

**Issue by Oosquai** [blaxxun-boop/Jewelcrafting#66]
Hi blaxxun-boop,
I like the Unsocket Dropped Items = Off setting in section 5 - Loot of the config.  I'm testing with Jewelcrafting as the only active mod, and I'm finding that this setting works in the sense that I can't drag gems out of their sockets.  Unfortunately, the vanilla game puts a Take All button in the bottom-left corner of the gem window, similar to a chest inventory window, and this button still removes gems despite this setting.
Thanks!

**Comment by blaxxun-boop** [comment]
Fixed in v1.5.0, thanks.

**Comment by Oosquai** [comment]
You rock!  Thank you!
