### ISSUE TITLE
Error with 1.5

### ISSUE THREAD

**Issue by Oosquai** [blaxxun-boop/Jewelcrafting#68]
Thanks for the super quick update to 1.5, but sadly I'm seeing an error in the BepInEx console now, and the game won't finish loading into a world until I disable jewelcrafting.
I tried a fresh world and fresh character, and that let me finish loading into a world!  I still see the following error though:

[Error  : Unity Log] InvalidOperationException: Sequence contains no matching element
Stack trace:
System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
(wrapper dynamic-method) Jewelcrafting.GemEffects.Necromancer+ReplaceAnimationController.DMD<Jewelcrafting.GemEffects.Necromancer+ReplaceAnimationController::Postfix>()
(wrapper dynamic-method) ZNetScene.DMD<ZNetScene::Awake>(ZNetScene)

**Comment by blaxxun-boop** [comment]
Means you have a mod that removes the bow from skeletons. I think Balrond has a mod like that.
