### ISSUE TITLE
ArgumentException

### ISSUE THREAD

**Issue by Horem** [blaxxun-boop/Jewelcrafting#7]
[Error  : Unity Log] ArgumentException: Cannot use any of the following characters in section and key names: = \n \t \ " ' [ ]
Parameter name: key
Stack trace:
BepInEx.Configuration.ConfigDefinition.CheckInvalidConfigChars (System.String val, System.String name) (at <2e96006724e44cef876346c4d9580850>:0)
BepInEx.Configuration.ConfigDefinition..ctor (System.String section, System.String key) (at <2e96006724e44cef876346c4d9580850>:0)
BepInEx.Configuration.ConfigFile.Bind[T] (System.String section, System.String key, T defaultValue, BepInEx.Configuration.ConfigDescription configDescription) (at <2e96006724e44cef876346c4d9580850>:0)
Jewelcrafting.Jewelcrafting.config[T] (System.String group, System.String name, T value, BepInEx.Configuration.ConfigDescription description, System.Boolean synchronizedSetting) (at <3acf56e6fdfe43bb9c0921fd5273b685>:0)
Jewelcrafting.Jewelcrafting+<>c__DisplayClass109_0.<AddBossBoxProgressConfig>b__0 (System.Int32 chance, System.Int32 i) (at <3acf56e6fdfe43bb9c0921fd5273b685>:0)
System.Linq.Enumerable+<SelectIterator>d__154`2[TSource,TResult].MoveNext () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Collections.Generic.LargeArrayBuilder`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] items) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Collections.Generic.EnumerableHelpers.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
Jewelcrafting.Jewelcrafting.AddBossBoxProgressConfig (System.String name, System.Int32[] progress) (at <3acf56e6fdfe43bb9c0921fd5273b685>:0)
Jewelcrafting.Jewelcrafting+AddBossBoxProgressConfigs.Postfix (ZNetScene __instance) (at <3acf56e6fdfe43bb9c0921fd5273b685>:0)
(wrapper dynamic-method) ZNetScene.DMD<ZNetScene::Awake>(ZNetScene)

Getting this with the latest build of JC.

**Comment by blaxxun-boop** [comment]
Hey,

this means, you have a boss with an unlocalized named e.g. [my_amazing_boss] in your game.
But it's fixed in v1.1.1 already.

Cheers.
