### ISSUE TITLE
Feature Suggestion - Sockets possible vs Sockets dropped.

### ISSUE THREAD

**Issue by Havengrad** [blaxxun-boop/Jewelcrafting#70]
I enjoy the ability to have up to ten sockets but I want to have to work for it, the calculations for Equipment drops tend to shoot towards the high end on sockets and I'd wish for some slider separation of "Max Sockets on an item" vs "Max sockets naturally occuring on drops"

**Comment by blaxxun-boop** [comment]
The mod is balanced for vanilla. The quality of the items dropped depends on the health of the creature. If your creatures have more HP than in vanilla, you have to adjust the config to make up for that.

**Comment by Havengrad** [comment]
While all the HP in my game is normal, I dug through all the settings one more time, just in case. SO I discovered that the reason I'd been unable to shift the bias of loot via the YML file was because there is a check box for it to even be observed. After testing and just ramping the number stupid high all my loot seems to be sitting comfortably at 1 socket each. This will suit my purposes and allow me to increase difficulty without the loot sneaking higher in turn.
