### ISSUE TITLE
Suggestion - extra socket(s) on celestial weapons?

### ISSUE THREAD

**Issue by Oosquai** [blaxxun-boop/Jewelcrafting#74]
Hi blaxxun-boop,
Would you consider offering a config to allow extra sockets on celestial weapons compared to other gear?
Thanks!

**Comment by blaxxun-boop** [comment]
Copy paste this file into your config folder: https://github.com/blaxxun-boop/Jewelcrafting/blob/master/Jewelcrafting/WorldBosses/Jewelcrafting.Gacha.yml

Add as many sockets as you want.

**Comment by Oosquai** [comment]
Thank you so much for the help!  I'm a little confused though.  I think
that would let me modify celestial weapons that dropped from events, but
what about celestial weapons in general?  If someone trades 5 coins in to
get one, I want them to be able to take it to their jewelcrafting bench and
punch 4 sockets into it instead of 3.  I tried only this in the file, but
it just yells at me and wants the first line to be an event:
celestial bone pickaxe:
  sockets:
    - empty
    - empty
    - empty
    - empty

Any tips please?
Thank you!
