### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by AMORAKI** [blaxxun-boop/Jewelcrafting#75]
Hi. Can you make it possible to use custom translations for this mod. I have already updated the Russian localisation, I will edit the translation to a more correct version as needed. And also not all text is added to the English translation so that a full translation into other languages can be made.
https://github.com/AMORAKI/Valheim-Jewelcrafting-RU/tree/main/translations

**Comment by blaxxun-boop** [comment]
Just put the translation file into the config folder, as Jewelcrafting.Russian.yml
If you want me to update the internal translations, simply create a PR.

**Comment by blaxxun-boop** [comment]
That's because they are added by another mod.

**Comment by AMORAKI** [comment]
Sorry. I didn’t immediately realize that it was added by another mod. PR i create. Little offtop: Your another mod "CreatureLevelAndLootControl" didnt have github page where i can create PR for translate ?
