### ISSUE TITLE
Unable to equip wishbone

### ISSUE THREAD

**Issue by Drudicta** [blaxxun-boop/Jewelcrafting#79]
I'm using Jewelcrafting and I'm unable to equip the wishbone, nor unequip it if I used vanilla to equip it. I've tried it with just jewelcrafting alone.

**Comment by blaxxun-boop** [comment]
It's a gem, not a utility item. You socket it into a utility item, instead of equipping it. This allows you to use the wishbone and your belt, ring, necklace, ... at the same time. You can change that in the config.
