### ISSUE TITLE
Enabling JewelCrafting with Wishbone Equipped Should Unequip Wishbone

### ISSUE THREAD

**Issue by Recon419A** [blaxxun-boop/Jewelcrafting#80]
Enabling JewelCrafting with a wishbone equipped causes the gem version of it to be non-removably equipped despite not being equipment, which puts it in a weird, buggy state. If there's a "disequip item" trigger, it should probably be called as part of initialization. Won't affect new worlds, only those where the item type of wishbone is changed mid-playthrough.

**Comment by max-fluff** [comment]
Got similar issue: 
Enabling JewelCrafting in existing world with wishbone in inventory makes it non-equippable. Disabling JewelCrafting fixes the issue

**Comment by blaxxun-boop** [comment]
@max-fluff: Either disable the config that turns the Wishbone into a gem or just socket it into a utility item. It's intended behaviour.

**Comment by max-fluff** [comment]
> @max-fluff: Either disable the config that turns the Wishbone into a gem or just socket it into a utility item. It's intended behaviour.

Thanks for reply! Maybe you should add some info on that on mod page, cuz it's not obvious at all.

**Comment by blaxxun-boop** [comment]
It's in the items description.
