### ISSUE TITLE
No damage taken when hitting the ground when you cancel glider

### ISSUE THREAD

**Issue by prikkeldraad** [blaxxun-boop/Jewelcrafting#81]
When you cancel the glider effect in mid air, it doesn't matter how high the drop is, you won't take fall damage.
Tested with Wolf Cape and Perfect Emerald.

Expected behaviour: when you fall you will take damage as normally, so when the glider effect is cancelled (with space bar) during mid flight, damage from the drop should be applied.

**Comment by blaxxun-boop** [comment]
That's exactly how it's supposed to work. You get the buff that prevents fall damage and can toggle the slow fall on and off while the effect lasts.
