### ISSUE TITLE
[Request] Nearest neighbor texture filtering

### ISSUE THREAD

**Issue by ignamiranda** [blaxxun-boop/Jewelcrafting#85]
From what I can tell, the textures in this mod use linear filtering instead of the sharp blocky pixel style of the vanilla game. I'd like the option to use nearest neighbor filtering for that pixelated look.

**Comment by blaxxun-boop** [comment]
Added an option for that in v1.5.14

**Comment by ignamiranda** [comment]
Hell yeah! Thank you
