### ISSUE TITLE
Mod deletes all equipment and food and leaves only Moder's Ring

### ISSUE THREAD

**Issue by Tempuser8734** [blaxxun-boop/Jewelcrafting#87]
When equiping Moder's Ring when Strength Belt is on both items are equipped.
When moving items in/from inventory those items change place between equipped slot and normal inventory slots.
After exiting and loading game, all items except the ring get deleted.
Any fix?

**Comment by sf754** [comment]
yeah same issue happened for me

**Comment by blaxxun-boop** [comment]
"Equipped slot"? Sounds like you are using a mod that adds dedicated equipment slots. Nothing to do with Jewelcrafting.
