### ISSUE TITLE
Not an Issue. I love the mod. One suggestion

### ISSUE THREAD

**Issue by Cooter22** [blaxxun-boop/Jewelcrafting#88]
Add gem clusters to leviathans. Im not sure if this is possible but would be a cool dynamic. Do you spend time on gems or chitin?

Some gems could be aquamarine, salt (spirit dmg), or maybe something I haven't thought of.

Great work on the mod. Its fantastic 👏

**Comment by blaxxun-boop** [comment]
There will be an ocean gem, once iron gate adds more content to the ocean.
Also, thanks for the kind words, I really appreciate it.
