### ISSUE TITLE
Feature Request: Add a config to control the spawn distance, density, location and number of drops.

### ISSUE THREAD

**Issue by Onins** [blaxxun-boop/Jewelcrafting#92]
Add a config to control the spawn distance and spawn density for gemstones. 
Also a config to control on which biome or dungeons, caves, camps every type of gems can spawn to.
Another config to control the drop quantity on each gem.

Also support other mods that extends the gems (Comfort Tweaks, Groups, Epic Jewels)

The problem is that the gem formation is very cluttered in a way that the gems can be clustered too much in an area especially when running many different types of gems in the game. If only we can control this via config that would be very helpful. Thanks

**Comment by blaxxun-boop** [comment]
You can decrease the density in the config, even for gems added by other mods.
