### ISSUE TITLE
Map pin of world bosses set in low orbit

### ISSUE THREAD

**Issue by Planetmind** [blaxxun-boop/Jewelcrafting#94]
So my understanding of map pins and pings is that, in addition to longitude and latitude, they store the elevation of the player who places them at the time of creation. However, when a world boss spawns somewhere on the map, the pin of it's location is given an altitude of I don't even know what, 1,000,000 meters? Kinda wacky.
In a vacuum, this wouldn't cause any noticeable problems. But when you add the mod [Waypoints](https://thunderstore.io/c/valheim/p/RustyMods/Waypoints/) and use a waypoint to teleport straight to the boss, it puts you at that absurd elevation directly above the boss. Took me a good 20 minutes to hit the ground when I tried it.
The solution I would recommend just for mod compatibility's sake is probably obvious, but I'll spell it out anyway. When spawning a frozen world boss, include the altitude of the world boss, plus a few meters, in the map pin so Waypoints, or any other mod that uses map pins to function, can use it's correct location. Thank you.

**Comment by Planetmind** [comment]
Found it happening in my BepInEx log, here's a quick screenshot.
![image](https://github.com/user-attachments/assets/505f7617-561c-4ddd-b4aa-1af8d5a2f8a8)

**Comment by blaxxun-boop** [comment]
It's the time when the boss spawned in, so the bosses survive a server restart and the server can properly clean up expired world bosses.

But what you've mentioned is clearly a bug in Waypoints anyway. The way teleportation in Valheim works is that it teleports you way below the terrain and then pushes you back up, until you stand on the terrain. Waypoints shouldn't set a Y coordinate during teleportation and just do it the vanilla way. Spawn the player below the surface and let Valheim handle the rest.
