### ISSUE TITLE
Celestial Weapon Config Changes not working

### ISSUE THREAD

**Issue by GracefulUni** [blaxxun-boop/Jewelcrafting#97]
Is it currently not possible to add a crafting recipe to the celestials weapons?

I have added GachaCoins, StandardPurpleSocket and Blackwood as the base crafting cost for all celestial weapons and the crafting station is on Forge with level 1-4.

I made sure to get ALL the materials but it doesnt show up in the Forge

**Comment by blaxxun-boop** [comment]
Will be fixed in the next release.
