### ISSUE TITLE
Mirror Mirror Images Setting for Gems not respecting

### ISSUE THREAD

**Issue by GracefulUni** [blaxxun-boop/Jewelcrafting#98]
I have used the Blessed crystal Mirror to duplicate my Black Perfect Gem, I got another Mirror and I was able to put in the Duplicated Gem and got another one.
Isn't this setting suppose to count towards any mirrored type items or is this setting only for the  Celestial crystal Mirror for Armor/Weapons?

**Comment by blaxxun-boop** [comment]
This only affects the celestial crystal mirror, yes. The gems do not know that they are mirror images.
