### ISSUE TITLE
Cant insert ring in ring in a box

### ISSUE THREAD

**Issue by Onins** [blaxxun-boop/Jewelcrafting#99]
![image](https://github.com/user-attachments/assets/9a024508-40b9-40b3-8a5d-5d0c84a41c24)

What is the usual cause of this?

**Comment by blaxxun-boop** [comment]
A mod messing with item stands. No idea which one, since you didn't provide any logs. Last time, it was a mod called Vanity Items?

**Comment by Onins** [comment]
Thank you for the input, ill check which mods messing with item stands

**Comment by Onins** [comment]
Found the issue. In my case its CircletExtended that was messing with the item stands.
